### ISSUE TITLE
Navigating the Resultset is lagging

### ISSUE THREAD

**Issue by LeanderK** [DifferentLink/Grape#256] opened 2018-03-05 14:28 UTC
When navigating the resultset using the keyboard, the application quickly becomes unresponsive and only recovers later.

**Comment by grecht** [comment] 2018-03-05 16:23
How big was the resultset? My machine navigates a database of ~80 graphs smoothly.

**Comment by DifferentLink** [comment] 2018-03-05 21:33
I can't reproduce this either. Navigating a database with almost 200 graphs works smoothly for me.

**Comment by grecht** [comment] 2018-03-06 14:40
@DifferentLink Maybe this is an OS-specific problem once again... :grin:

**Comment by LeanderK** [comment] 2018-03-06 14:46
I would put this issue on hold for our weekly meeting.

**Comment by grecht** [comment] 2018-03-08 12:31
Closed as issue could not be reproduced on Linux/Windows

**Closed by grecht** 2018-03-08 12:31 UTC
